### ISSUE TITLE
Error: Cannot read config file: /../../Desktop/zksync-starter/packages/eslint-config-custom/index.js

### ISSUE THREAD

**Issue by sellmon** [ewerx/zksync-starter#1]
Hello, I encountered a problem when launching the project. What could be the reason?

```
Error: Cannot read config file: /Users/sllmn/Desktop/zksync-starter/packages/eslint-config-custom/index.js
Error: Cannot find module 'next/babel'
Require stack:
- /Users/sllmn/Desktop/zksync-starter/packages/eslint-config-custom/index.js
- /Users/sllmn/Desktop/zksync-starter/node_modules/.pnpm/@eslint+eslintrc@0.4.3/node_modules/@eslint/eslintrc/lib/config-array-factory.js
- /Users/sllmn/Desktop/zksync-starter/node_modules/.pnpm/@eslint+eslintrc@0.4.3/node_modules/@eslint/eslintrc/lib/index.js
- /Users/sllmn/Desktop/zksync-starter/node_modules/.pnpm/eslint@7.32.0/node_modules/eslint/lib/cli-engine/cli-engine.js
- /Users/sllmn/Desktop/zksync-starter/node_modules/.pnpm/eslint@7.32.0/node_modules/eslint/lib/cli-engine/index.js
- /Users/sllmn/Desktop/zksync-starter/node_modules/.pnpm/eslint@7.32.0/node_modules/eslint/lib/api.js
- /Applications/WebStorm.app/Contents/plugins/JavaScriptLanguage/languageService/eslint/bin/eslint-common.js
- /Applications/WebStorm.app/Contents/plugins/JavaScriptLanguage/languageService/eslint/bin/eslint-plugin.js
- /Applications/WebStorm.app/Contents/plugins/JavaScriptLanguage/languageService/eslint/bin/eslint-plugin-provider.js
- /Applications/WebStorm.app/Contents/plugins/JavaScriptLanguage/jsLanguageServicesImpl/js-language-service.js
Referenced from: /Users/sllmn/Desktop/zksync-starter/.eslintrc.js

Error: Cannot read config file: /Users/sllmn/Desktop/zksync-starter/packages/eslint-config-custom/index.js
Error: Cannot find module 'next/babel'
Require stack:
- /Users/sllmn/Desktop/zksync-starter/packages/eslint-config-custom/index.js
- /Users/sllmn/Desktop/zksync-starter/node_modules/.pnpm/@eslint+eslintrc@0.4.3/node_modules/@eslint/eslintrc/lib/config-array-factory.js
- /Users/sllmn/Desktop/zksync-starter/node_modules/.pnpm/@eslint+eslintrc@0.4.3/node_modules/@eslint/eslintrc/lib/index.js
- /Users/sllmn/Desktop/zksync-starter/node_modules/.pnpm/eslint@7.32.0/node_modules/eslint/lib/cli-engine/cli-engine.js
- /Users/sllmn/Desktop/zksync-starter/node_modules/.pnpm/eslint@7.32.0/node_modules/eslint/lib/cli-engine/index.js
- /Users/sllmn/Desktop/zksync-starter/node_modules/.pnpm/eslint@7.32.0/node_modules/eslint/lib/api.js
- /Applications/WebStorm.app/Contents/plugins/JavaScriptLanguage/languageService/eslint/bin/eslint-common.js
- /Applications/WebStorm.app/Contents/plugins/JavaScriptLanguage/languageService/eslint/bin/eslint-plugin.js
- /Applications/WebStorm.app/Contents/plugins/JavaScriptLanguage/languageService/eslint/bin/eslint-plugin-provider.js
- /Applications/WebStorm.app/Contents/plugins/JavaScriptLanguage/jsLanguageServicesImpl/js-language-service.js
Referenced from: /Users/sllmn/Desktop/zksync-starter/.eslintrc.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Function.resolve (node:internal/modules/cjs/helpers:116:19)
    at Object.<anonymous> (/Users/sllmn/Desktop/zksync-starter/packages/eslint-config-custom/index.js:8:25)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at module.exports (/Users/sllmn/Desktop/zksync-starter/node_modules/.pnpm/import-fresh@3.3.0/node_modules/import-fresh/index.js:32:59)
    at loadJSConfigFile (/Users/sllmn/Desktop/zksync-starter/node_modules/.pnpm/@eslint+eslintrc@0.4.3/node_modules/@eslint/eslintrc/lib/config-array-factory.js:225:16)
Process finished with exit code -1

```
I performed the installation and immediately encountered these errors.
Can you give advice how to fix that? Thanks!

**Comment by ewerx** [comment]
Not sure what is causing this in your case, but check out this thread on SO for possible solutions: https://stackoverflow.com/questions/68163385/parsing-error-cannot-find-module-next-babel
